### PR TITLE
Style results panel

### PR DESCRIPTION
**Pull request by kacyhulme**
Fixes [this To Do](https://3.basecamp.com/3097764/buckets/19037960/todos/3083309927)

### Testing notes

1. Results panel should now match design
2. Minor styling updates to left panel should now match design

### CODE REVIEW

**Comment by codegoalie** [comment]
@kacyhulme I added a few things here to move this along. It seems like this is good to go. Would you mind taking a look and if so, we can merge and hand off to Bruno for design review? Thanks!

**Review by codegoalie — CHANGES_REQUESTED** [review]
@kacyhulme Actually one more thing I just noticed, the inputs that are percentages should have a `%` instead of a dollar sign as their "icon".

image

**Comment by kacyhulme** [comment]
@codegoalie Looks like I was making changes the same time you were. I just fixed that $ and % swap.

**Review by codegoalie — CHANGES_REQUESTED** [review]
Few small items I'm seeing:

1. Headers are not aligned.
1. There's a little border above the first dot which I think is due to the dot being a few pixels too low (rather than vertically centered with the headers).

image

**Comment by kacyhulme** [comment]
@codegoalie Small adjustment to fix the alignment of the headers and the progress bar dot. Should be aligned now and match designs.

**Review by codegoalie — APPROVED** [review]
Looks good!! :shipit:

**Pull request merged**
