### PR TITLE
Input component

### PR DESCRIPTION
**Pull request by kacyhulme**
Basic Input component with basic gt-brand styles to help get set up.

### CODE REVIEW

**Review by codegoalie — APPROVED** [review]
Looks good!! We could use styled-components if you wanted too.

**Review by codegoalie — CHANGES_REQUESTED** [review]
Just noticed the icon looks off by one pixel:

image

Also, we'll have percentage and radio inputs too, should we attach the icon to the input instead of the wrapper?

**Comment by kacyhulme** [comment]
I was thinking about using styled-components, because then that way we could pull over the radio button from gu-assessment.

**Comment by kacyhulme** [comment]
That :before should be aligned now that the fonts have been corrected.

**Comment by codegoalie** [comment]
:100: on styled-components and re-using the radio buttons

**Pull request merged**
