### PR TITLE
Add fonts

### PR DESCRIPTION
**Pull request by kacyhulme**
Adds font files and includes font family styles.

### CODE REVIEW

**Comment by codegoalie** [comment]
@kacyhulme Is this working for you? It doesn't look like it is for me.

image

Do we need to define the `@font-face`?

**Comment by kacyhulme** [comment]
@codegoalie Added font-face and realigned $.

**Comment by codegoalie** [comment]
This looks good. I'll merge this in favor of #1

**Review by codegoalie — APPROVED** [review]
Looking good now. Merging this and closing #1

**Pull request merged**
